BachettiRepres/BachettiRepres/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include("mostruario.urls")),
    path('admin/', admin.site.urls),
]

BachettiRepres/mostruario/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("empresa/<int:id>/", views.company_page, name="company" ),
    path("empresa/<int:id_emp>/tipo/<int:id_tip>/", views.products_page, name="products"),
    path("empresa/<int:id_emp>/tipo/<int:id_tip>/produto/<int:id_pro>/", views.product_page, name="product"),
]

BachettiRepres/mostruario/models.py
from django.db import models
from django.contrib.postgres.fields import ArrayField

class Empresa(models.Model):
    nome = models.CharField(max_length=80)
    descricao = models.CharField(max_length=200, null=True, blank=True)
    link_imagem = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return self.nome

class Tipo_Produto(models.Model):
    nome = models.CharField(max_length=80)
    empresa = models.ForeignKey('Empresa',on_delete=models.CASCADE,)

    def __str__(self):
        return self.nome

class Produto(models.Model):
    nome = models.CharField(max_length=80)
    descricao = models.CharField(max_length=200, null=True, blank=True)
    tipo = models.ForeignKey('Tipo_Produto',on_delete=models.CASCADE,)
    link_imagem_principal = models.CharField(max_length=200, null=True, blank=True)
    link_imagens_extras = ArrayField(models.CharField(max_length=200), blank=True, default=list)

    def __str__(self):
        return self.nome

BachettiRepres/mostruario/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Empresa, Tipo_Produto, Produto

def home(request):
    return render(request, 'home.html')

def company_page(request, id):
    tipos = Tipo_Produto.objects.filter(empresa_id=id)
    context={
        'tipos': tipos,
    }
    return render(request, 'company_page.html', context)

def products_page(request, id_emp, id_tip):
    produtos = Produto.objects.filter(tipo_id=id_tip)
    context={
        'produtos': produtos
    }
    return render(request, 'product_page.html', context)

def product_page(request, id_emp, id_tip, id_pro):
    produto = get_object_or_404(Produto, id=id_pro)

    return render(request, 'product.html', {'produto': produto})

BachettiRepres/mostruario/templates/company_page.html
{% extends "main.html" %}
{% block title %} HOME {% endblock %}

{% block content %}

<div class="tipos-page">
    {% for tipo in tipos %}
        <div class="tipos">
            <a href="/empresa/{{tipo.empresa_id}}/tipo/{{tipo.id}}">
                <div class="tipos-text">{{tipo.nome}}</div>
            </a>
        </div>
    {% endfor %}
</div>

{% endblock %}

BachettiRepres/mostruario/templates/home.html
{% extends "main.html" %}
{% block title %} HOME {% endblock %}

{% block content %}

<div class="companies">
    {% for empresa in empresas %}
        <div class="company">
            <a href="/empresa/{{ empresa.id }}" class="company-link">
                <img src="{{ empresa.link_imagem }}" alt="Empresa Image" class="empresa-image" />
            </a>
        </div>
    {% endfor %}
</div>

{% endblock %}

BachettiRepres/mostruario/templates/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'main.css' %}">
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body>

    <div class="header">
        <img src="{% static 'logo.png' %}" width="250vh"/>
    </div>

    <button class="sidenav-toggle" onclick="toggleNav()">☰</button>

    <div class="sidenav" id="mySidenav">
        <a href="{% url 'home' %}">Início</a>
        {% for empresa in empresas %}
            <button class="dropdown-btn">{{ empresa.nome }} 
                <i class="fa fa-caret-down"></i>
            </button>
            <div class="dropdown-container">
                {% for tipo in empresa.tipo_produto_set.all %}
                    <a href="/empresa/{{tipo.empresa_id}}/tipo/{{tipo.id}}">{{ tipo.nome }}</a>
                {% endfor %}
            </div>
        {% endfor %}
        <a href="https://wa.me/553284734389">Whatsapp</a>
    </div>

    <div id="content", name="content", class="content">
        {% block content %}
        {% endblock %}
    </div>

    <script>
        var isOpen = true;

        function toggleNav() {
            var sidenav = document.getElementById("mySidenav");
            var content = document.getElementById("content");
            var header = document.querySelector(".header");
            var toggleBtn = document.querySelector(".sidenav-toggle");

            if (isOpen) {
                sidenav.classList.add("closed");
                content.classList.add("closed");
                header.classList.add("closed");
                toggleBtn.classList.add("closed");
            } else {
                sidenav.classList.remove("closed");
                content.classList.remove("closed");
                header.classList.remove("closed");
                toggleBtn.classList.remove("closed");
            }
            isOpen = !isOpen;
        }


        // Dropdown functionality
        var dropdown = document.getElementsByClassName("dropdown-btn");
        for (let i = 0; i < dropdown.length; i++) {
            dropdown[i].addEventListener("click", function() {
                this.classList.toggle("active");
                var dropdownContent = this.nextElementSibling;
                dropdownContent.style.display = dropdownContent.style.display === "block" ? "none" : "block";
            });
        }
    </script>

</body>
</html>

BachettiRepres/mostruario/templates/product.html
{% extends "main.html" %}
{% block title %} HOME {% endblock %}

{% block content %}

<div class="container-cols">
    <div class="col col-1">
        <section class="container-slider">
            <div class="slider-wrapper">
                <div class="slider">
                    <img id="slide-1" src={{produto.link_imagem_principal}} alt="slide 1"/>
                    {% if produto.link_imagens_extras %}
                        {% for imagem in produto.link_imagens_extras %}
                            <img id="slide-{{ forloop.counter|add:1 }}" src="{{ imagem }}" alt="slide {{ forloop.counter|add:1 }}"/>
                        {% endfor %}
                    {% endif %}
                </div>
                <div class="slider-nav">
                    <a href="#slide-1"></a>
                    {% if produto.link_imagens_extras %}
                        {% for imagem in produto.link_imagens_extras %}
                            <a href="#slide-{{ forloop.counter|add:1 }}"></a>
                        {% endfor %}
                    {% endif %}
                </div>
            </div>
        </section>
    </div>
    <div class="col col-2">
        <div class="produto-text">{{ produto.nome }}</div>
        <br>
        <div class="produto-desc">{{ produto.descricao }}</div>
    </div>
</div>

{% endblock %}

BachettiRepres/mostruario/templates/product_page.html
{% extends "main.html" %}
{% block title %} HOME {% endblock %}

{% block content %}

<div class="produtos-page">
    {% for produto in produtos %}
        <div class="produtos">
            <a href="/empresa/{{produto.tipo.empresa.id}}/tipo/{{produto.tipo_id}}/produto/{{produto.id}}">
                <div class="produtos-text">{{produto.nome}}</div>
                <img src="{{ produto.link_imagem_principal }}" alt="Produto Image" class="produtos-image" />
            </a>
        </div>
    {% endfor %}
</div>

{% endblock %}